services:
  backend:
    build: ./backend
    container_name: ecf_backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - backend_vendor:/var/www/html/vendor
    depends_on:
      - db
      - mongo

  db:
    image: mysql:8.0
    container_name: ecf_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: innovevents
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecf_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

  mongo:
    image: mongo:latest
    container_name: ecf_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: ecf_mongo_express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo

  mailhog:
    image: mailhog/mailhog
    container_name: ecf_mailhog
    ports:
      - "1025:1025"
      - "8090:8025"

  mobile:
    build: ./mobile
    container_name: ecf_mobile
    ports:
      - "4300:4300"
    volumes:
      - ./mobile:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  db_data:
  mongo_data:
  backend_vendor:
